---
- name: configure zfs auto snapshot
  shell: |
    zfs set com.sun:auto-snapshot=false zroot
    zfs set com.sun:auto-snapshot=false zroot/data
    zfs set com.sun:auto-snapshot=true zroot/data/home
    zfs set com.sun:auto-snapshot:frequent=false dpool/data/home
    zfs set com.sun:auto-snapshot:monthly=false dpool/data/home
    zfs set com.sun:auto-snapshot:hourly=false dpool/data/home
    zfs set com.sun:auto-snapshot:weekly=false dpool/data/home
    zfs set com.sun:auto-snapshot:daily=true dpool/data/home

- name: setup daily zfs scrub
  copy:
    src: zscrub
    dest: /etc/cron.weekly/
    mode: 0755
